/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        positive: '#fff',
        inverse: '#000000',
        brand: 'brand',
        black: 'black',
        success: 'success',
        error: 'error',
        warning: 'warning',
        white: {
          1: 'rgba(0, 0, 0, 0.8)',
          2: 'rgba(0, 0, 0, 0.72)',
          3: 'rgba(0, 0, 0, 0.64)',
          4: 'rgba(0, 0, 0, 0.52)',
          5: 'rgba(0, 0, 0, 0.75)',
          6: 'rgba(0, 0, 0, 0.45)',
          7: 'rgba(0, 0, 0, 0.15)',
          8: 'positive',
        },
        'text-primary': '#000000',
        'text-title': '#000000',
        'text-second': '#000000',
        'text-third': '#000000',
        'text-fourth': '#000000',
        'text-disabled': '#999999',
        'text-inverse': 'positive',
        link: '#0076FF',
        primary: 'brand',
        disabled: '#5c5c5c',
        divider: '#474747',
        highlight: 'error',
        inverseBorder: 'rgba(0, 0, 0, 0.52)',
        inverseDivider: 'rgba(0, 0, 0, 0.52)',
        'box-body-light': '#E0E0E0',
        'box-body-dark': '#373a50',
        'box-body-disabled': '#474747',
        'box-border-light': '#474747',
        'box-border-dark': '#333333',
        'box-border-error': 'error',
        'box-border-disabled': '#474747',
        'box-border-hover': '#0d0c0c',
        'box-shadow': 'rgba(0,0,0,0.12)',
      },
      fontSize: {
        'text-s': '12px',
        'text-sm': '14px',
        'text-md': '16px',
        'text-lg': '20px',
      },
      fontWeight: {
        'text-regular': 400,
        'text-medium': 600,
      },
      spacing: {
        'box-padding-zero': '0px',
        'box-padding-mini': '4px',
        'box-padding-xs': '2px',
        'box-padding-s': '8px',
        'box-padding-sm': '12px',
        'box-padding-md': '16px',
        'box-padding-lg': '24px',
        'box-margin-zero': '0px',
        'box-margin-mini': '4px',
        'box-margin-xs': '2px',
        'box-margin-s': '8px',
        'box-margin-sm': '12px',
        'box-margin-md': '16px',
        'box-margin-lg': '24px',
        'box-height-mini': '16px',
        'box-height-xs': '20px',
        'box-height-s': '24px',
        'box-height-sm': '28px',
        'box-height-md': '32px',
        'box-height-lg': '38px',
        'box-width-minimum': '12px',
        'box-width-mini': '16px',
        'box-width-xs': '20px',
        'box-width-s': '24px',
        'box-width-sm': '28px',
        'box-width-md': '32px',
        'box-width-lg': '64px',
      },
      borderRadius: {
        box: '2px',
      },
      boxShadow: {
        'box-shadow-top': '0px 2px 12px 0px rgba(0,0,0,0.12)',
      },
      borderWidth: {
        'box-border-regular': '1px',
        'box-border-error': '1px',
      },
      lineHeight: {
        text: 1.5715,
      },
    },
  },
  plugins: [],
};
